version: "3"

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=root
    ports:
      - '27017:27017'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local